informesHandler:
  name: ${self:custom.base}-informes
  handler: services/informes/src/handler.main
  events:
    - httpApi: 'GET /informe/users/{acceso}/{start}/{end}/{nombre}'
    - httpApi: 'GET /informe/pedidos/{type}/{start}/{end}/{nombre}'
    - httpApi: 'GET /informe/vehiculos/{start}/{end}/{nombre}'
    - httpApi: 'GET /informe/tanques/{start}/{end}/{nombre}'
    - httpApi: 'GET /informe/revisiones/{start}/{end}/{nombre}'
    - httpApi: 'GET /informe/frecuencias/{start}/{end}/{nombre}'
  package:
    include:
      - services/informes/src/handler.js
      - services/informes/src/get-users.js
      - services/informes/src/get-pedidos.js
      - services/informes/src/get-vehiculos.js
      - services/informes/src/get-tanques.js
      - services/informes/src/get-revisiones.js
      - services/informes/src/get-frecuencias-informe.js
      - lib/connection-pg.js
      - lib/errors/database-error.js
      - lib/informe-response.js
