CREATE OR REPLACE FUNCTION revisiones()
  RETURNS TABLE (
    revision_id INTEGER,
    creado timestamp,
    sector character varying,
    barrio character varying,
    propiedad character varying,
    lote character varying,
    usuarios_atendidos character varying,
    m3 character varying,
    n_medidor_text character varying,
    n_medidor character varying[],
    n_comodato_text character varying,
    n_comodato character varying[],
    ubicacion character varying,
    poblado character varying,
    ciudad character varying,
    dpto character varying,
    isometrico character varying[],
    otros_comodato character varying[],
    soporte_entrega character varying[],
    punto_consumo character varying[],
    visual character varying[],
    protocolo_llenado character varying[],
    hoja_seguridad character varying[],
    otros_si character varying[],
    observaciones character varying,
    solicitud_servicio character varying,
    usuario_solicita INTEGER,
    avisos BOOLEAN,
    extintores BOOLEAN,
    distancias BOOLEAN,
    electricas BOOLEAN,
    accesorios BOOLEAN,
    alerta character varying[],
    alerta_text character varying,
    alerta_fecha character varying,
    n_acta character varying,
    activo BOOLEAN,
    eliminado BOOLEAN,
    usuario_crea INTEGER,
    tanque_id INT[],
    documento character varying[],
    dep_tecnico character varying[],
    dep_tecnico_text character varying,
    dep_tecnico_estado BOOLEAN,
    usuario_id INTEGER,
    punto_id INT[],
    estado INTEGER,
    capacidad character varying,
    placa_text character varying,
    fabricante character varying,
    registro_onac character varying,
    fecha_ultima_rev character varying,
    n_placa character varying,
    codigo_activo character varying,
    serie character varying,
    ano_fabricacion character varying,
    existe_tanque character varying,
    ultim_rev_total character varying,
    tanque_propiedad character varying,
    tanque_usuario_id INTEGER,
    tanque_usuario_crea INTEGER,
    zona_id INTEGER,
    tanque_placa character varying[],
    tanque_placa_mantenimiento character varying[],
    tanque_placa_fabricante character varying[],
    tanque_dossier character varying[],
    tanque_cer_fabricante character varying[],
    tanque_cer_onac character varying[],
    tanque_visual character varying[]
  )
AS $$
BEGIN
  RETURN QUERY
    SELECT
      r._id AS revision_id,
      r.creado,
      r.sector,
      r.barrio,
      r.propiedad,
      r.lote,
      r.usuariosAtendidos AS usuarios_atendidos,
      r.m3,
      r.nMedidorText AS n_medidor_text,
      r.nMedidor,
      r.nComodatoText AS n_comodato_text,
      r.nComodato,
      r.ubicacion,
      r.poblado,
      r.ciudad,
      r.dpto,
      ARRAY_AGG(r.isometrico) AS isometrico,
      ARRAY_AGG(r.otrosComodato) AS otros_comodato,
      ARRAY_AGG(r.soporteEntrega) AS soporte_entrega,
      ARRAY_AGG(r.puntoConsumo) AS punto_consumo,
      ARRAY_AGG(r.visual) AS visual,
      ARRAY_AGG(r.protocoloLlenado) AS protocolo_llenado,
      ARRAY_AGG(r.hojaSeguridad) AS hoja_seguridad,
      ARRAY_AGG(r.otrosSi) AS otros_si,
      r.observaciones,
      r.solicitudServicio AS solicitud_servicio,
      r.usuarioSolicita AS usuario_solicita,
      r.avisos,
      r.extintores,
      r.distancias,
      r.electricas,
      r.accesorios,
      ARRAY_AGG(r.alerta) AS alerta,
      r.alertaText AS alerta_text,
      r.alertaFecha AS alerta_fecha,
      r.nActa AS n_acta,
      r.activo,
      r.eliminado,
      r.usuarioCrea AS usuario_crea,
      ARRAY_AGG(t._id) AS tanque_id,
      ARRAY_AGG(r.documento) AS documento,
      ARRAY_AGG(r.depTecnico) AS dep_tecnico,
      r.depTecnicoText AS dep_tecnico_text,
      r.depTecnicoEstado AS dep_tecnico_estado,
      r.usuarioId AS usuario_id,
      ARRAY_AGG(r.puntoId) AS punto_id,
      r.estado,
      t.capacidad,
      t.placaText AS placa_text,
      t.fabricante,
      t.registroOnac AS registro_onac,
      t.fechaUltimaRev AS fecha_ultima_rev,
      t.nPlaca AS n_placa,
      t.codigoActivo AS codigo_activo,
      t.serie,
      t.anoFabricacion AS ano_fabricacion,
      t.existeTanque AS existe_tanque,
      t.ultimRevTotal AS ultim_rev_total,
      t.propiedad AS tanque_propiedad,
      t.usuarioId AS tanque_usuario_id,
      t.usuarioCrea AS tanque_usuario_crea,
      t.zonaId,
      ARRAY_AGG(t.placa) AS tanque_placa,
      ARRAY_AGG(t.placaMantenimiento) AS tanque_placa_mantenimiento,
      ARRAY_AGG(t.placaFabricante) AS tanque_placa_fabricante,
      ARRAY_AGG(t.dossier) AS tanque_dossier,
      ARRAY_AGG(t.cerFabricante) AS tanque_cer_fabricante,
      ARRAY_AGG(t.cerOnac) AS tanque_cer_onac,
      ARRAY_AGG(t.visual) AS tanque_visual
    FROM revisiones r
    JOIN puntos p ON r.puntoId = p._id
    JOIN tanques t ON t._id = ANY(r.tanqueId)
    WHERE t._id IS NOT NULL
    GROUP BY
      r._id,
      r.creado,
      r.sector,
      r.barrio,
      r.propiedad,
      r.lote,
      r.usuariosAtendidos,
      r.m3,
      r.nMedidorText,
      r.nMedidor,
      r.nComodatoText,
      r.nComodato,
      r.ubicacion,
      r.poblado,
      r.ciudad,
      r.dpto,
      r.observaciones,
      r.solicitudServicio,
      r.usuarioSolicita,
      r.avisos,
      r.extintores,
      r.distancias,
      r.electricas,
      r.accesorios,
      r.alertaText,
      r.alertaFecha,
      r.nActa,
      r.activo,
      r.eliminado,
      r.usuarioCrea,
      r.depTecnicoText,
      r.depTecnicoEstado,
      r.usuarioId,
      r.estado,
      t.capacidad,
      t.placaText,
      t.fabricante,
      t.registroOnac,
      t.fechaUltimaRev,
      t.nPlaca,
      t.codigoActivo,
      t.serie,
      t.anoFabricacion,
      t.existeTanque,
      t.ultimRevTotal,
      t.propiedad,
      t.usuarioId,
      t.usuarioCrea,
      t.zonaId;

  RETURN;
END;
$$ LANGUAGE plpgsql;
