source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby "2.6.10"

# Use compatible versions for Ruby 2.6.10
gem 'cocoapods', '~> 1.12.0'
gem 'activesupport', '~> 6.1.7', '< 7.0'
gem 'xcodeproj', '< 1.26.0'
