createPunto:
  name: ${self:custom.base}-create-punto
  handler: services/puntos/src/create-punto.main
  events:
    - httpApi: 'POST /pun/punto'
  package:
    include:
      - services/puntos/src/create-punto.js
      - lib/errors/database-error.js

createPuntoVarios:
  name: ${self:custom.base}-create-punto-varios
  handler: services/puntos/src/create-punto-varios.main
  events:
    - httpApi: 'POST /pun/punto/create-varios'
  package:
    include:
      - services/puntos/src/create-punto-varios.js
      - lib/errors/database-error.js

updatePuntoVarios:
  name: ${self:custom.base}-update-punto-varios
  handler: services/puntos/src/update-punto-varios.main
  events:
    - httpApi: 'POST /pun/punto/update-varios'
  package:
    include:
      - services/puntos/src/update-punto-varios.js
      - lib/errors/database-error.js

deletePunto:
  name: ${self:custom.base}-delete-punto
  handler: services/puntos/src/delete-punto.main
  events:
    - httpApi: 'DELETE /pun/punto'
  package:
    include:
      - services/puntos/src/delete-punto.js
      - lib/errors/database-error.js

getPunto:
  name: ${self:custom.base}-get-puntos
  handler: services/puntos/src/get-punto.main
  events:
    - httpApi: 'GET /pun/punto'
  package:
    include:
      - services/puntos/src/get-punto.js
      - lib/errors/database-error.js

getPuntoById:
  name: ${self:custom.base}-get-punto-by-id
  handler: services/puntos/src/get-punto-by-id.main
  events:
    - httpApi: 'GET /pun/punto/byId/{_id}'
  package:
    include:
      - services/puntos/src/get-punto-by-id.js
      - lib/errors/database-error.js

getPuntoByClient:
  name: ${self:custom.base}-get-punto-by-client
  handler: services/puntos/src/get-punto-by-client.main
  events:
    - httpApi: 'GET /pun/punto/byCliente/{_id}'
  package:
    include:
      - services/puntos/src/get-punto-by-client.js
      - lib/errors/database-error.js

editCapacidad:
  name: ${self:custom.base}-edit-capacidad
  handler: services/puntos/src/edit-capacidad.main
  events:
    - httpApi: 'PUT /pun/punto/editaAlmacenamiento/{_id}/{capacidad}'
  package:
    include:
      - services/puntos/src/edit-capacidad.js
      - lib/errors/database-error.js

togglePuntoStatus:
  name: ${self:custom.base}-toggle-punto-status
  handler: services/puntos/src/toggle-punto-status.main
  events:
    - httpApi: 'PUT /pun/punto/toggle-status/{_id}/{activo}'
  package:
    include:
      - services/puntos/src/toggle-punto-status.js
      - lib/errors/database-error.js
